# Application
spring.application.name=tickets-service
server.port=8081

# PostgreSQL
spring.datasource.url=jdbc:postgresql://tickets-postgres-service:5432/ticketsdb
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=ticketsuser
spring.datasource.password=ticketspassword

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Initialize data.sql
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# SNS Configuration (LocalStack)
app.sns.enabled=true
app.sns.topic-arn=arn:aws:sns:us-east-1:000000000000:SNS-Topic
app.sns.queue-url=https://localhost.localstack.cloud:4566/000000000000/ticket-events-queue
app.sns.region=us-east-1
app.sns.queue-name=ticket-events-queue
app.sns.localstack-endpoint=https://localhost.localstack.cloud:4566