spring.application.name=poc
server.port=8080

# Configuração do PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5433/pocdb
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=pocuser
spring.datasource.password=pocpassword
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Configuração do JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.secret=b8f4c1e2a7d93f6c5e1a9b2d7f4c8a6e3b1d9f7a2c6e8b4d5f1a7c9e2b6d4f8
jwt.expiration=86400000

# Tickets Service
tickets.service.url=http://localhost:8081

# Notification Service
notification.service.url=http://localhost:8082
