spring.application.name=notification-service
server.port=8082

# SNS Configuration (LocalStack)
app.sns.enabled=true
app.sns.topic-arn=arn:aws:sns:us-east-1:000000000000:email-notification
app.sns.queue-url=https://localhost.localstack.cloud:4566/000000000000/email-notification-queue
app.sns.region=us-east-1
app.sns.queue-name=email-notification-queue
app.sns.localstack-endpoint=https://localhost.localstack.cloud:4566