spring.application.name=poc
server.port=8080

# Configuração do PostgreSQL Database
spring.datasource.url=jdbc:postgresql://postgres-service:5432/pocdb
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=pocuser
spring.datasource.password=pocpassword
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Configuração do JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.secret=mySecretKeyForJWTTokenGenerationAndValidationPurposesOnly1234567890
jwt.expiration=86400000


#V